// register

POST http://localhost:5000/Users
Content-Type: application/json

{
    "name": "Anisa",
    "email": "salsabilavebinatasya19@gmail.com",
    "password": "123456",
    "confPassword": "123456"
   

}

###
// get users

GET http://localhost:5000/Users

###

// get single users
GET http://localhost:5000/Users/15e40872-2694-4899-8206-fa57bf182c2a

###

// update user
PATCH  http://localhost:5000/Users/15e40872-2694-4899-8206-fa57bf182c2a
Content-Type: application/json

{
    "name": "Anisa",
    "email": "salsabilavebi68@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"

}

###

// delete 

DELETE  http://localhost:5000/Users/15e40872-2694-4899-8206-fa57bf182c2a

//Login 
### 
POST   http://localhost:5000/login
Content-Type: application/json

{
   
    "email": "salsabilavebinatasya19@gmail.com",
    "password": "123456"
    
}


###

GET   http://localhost:5000/me

### 
DELETE    http://localhost:5000/logout

###

http://localhost:5000/karyawans/

###
http://localhost:5000/Galeris/